### ISSUE TITLE
Debug renaming could cause BadImageException

### ISSUE THREAD

**Issue by wmjordan** [mkaring/ConfuserEx#161]
I was addressing a weird problem after upgrading to the recently released version 1.4. ~(The weird problem will be reported later if I could figure out which part may be the cause)~ I changed the rename setting to `debug`. The "protected" application could not run due to a `BadImageException` which complained that there were two type having the same name in the assembly.

I examined the assembly and found it probably had something to do with nested generic type.

````C#
static class X<T> {
   abstract class A { }
   internal sealed class B : A { }
   internal sealed class C : A { }
}
````

After the `debug` renaming, the `A`, `B`, `C` within `X<T>` will be renamed to `X`, which breaks the application.

EDIT: The weird problem disappeared after applying #163.

**Comment by mkaring** [comment]
@wmjordan: The other problem you noticed is very likely related to #162

**Comment by wmjordan** [comment]
The other problem does not seem to be related to Control Flow, which has already been explicitly removed.

Please try to fix this issue first so I can get on to address the other one.

**Comment by wmjordan** [comment]
Thank you for provided the quick fix.

"The other problem" had not occurred any more after downloading the file provided in #162.

**Comment by mkaring** [comment]
The debug renaming was broken in case there are classes with the same name in variants with different generic parameters.

**Comment by mkaring** [comment]
@wmjordan: Can you confirm that the issue is fixed for you in [this build][0]?

[0]: https://ci.appveyor.com/project/mkaring/confuserex/builds/34039576/artifacts

**Comment by wmjordan** [comment]
Still have problem, but from another aspect.
I will try to make a test case for you later.

**Comment by wmjordan** [comment]
The environment to reproduce the new problem is quite complicated.

1. Create a dynamic assembly, a module, and a generic static type.
2. The generic static type has a field.
3. The type of the field is a generic delegate, which is defined from the source code.
4. Make a generic type from the aforementioned type, get the runtime static field info.
5. Call the `GetValue(null)` to obtain the instance of the generic static field.

We will see the following exception:
````
System.TypeLoadException: Could not load type '_NAME_OF_DELEGATE`1' from assembly ....
````

It is OK when using other rename modes except the `debug` mode.

**Comment by mkaring** [comment]
@wmjordan: Could you please verify if the pull request #169 correctly implements the case you were describing and if [this build][0] fixes the issue?

[0]: https://ci.appveyor.com/project/mkaring/confuserex/builds/34047687/artifacts

**Comment by wmjordan** [comment]
Bravo!
The "protected" application is working without problem now.
